name: Compile LaTeX Document

on:
  push:
    branches:
      - main
    paths:
      - '**.tex'
      - '**.bib'
      - 'images/**'
      - '**.cls'
      - '**.sty'
      # Avoid Commit PDF causes infinity loop

jobs:
  compile_and_commit_latex:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          args: >-
            -pdf
            -xelatex
            -interaction=nonstopmode
            -file-line-error
            -halt-on-error

      - name: Commit and push PDF
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ci(build): add new pdf version"

          file_pattern: main.pdf
